# Generated by Django 5.2.1 on 2025-05-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('store', '0003_alter_variation_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation_product',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
